### PR TITLE
Add puppet-capsule to the hourly cron sync of git repos

### PR DESCRIPTION
**Pull request by cpeters**

### CODE REVIEW

**Comment by domcleal** [comment]
Is that the only module you intend to add?

**Comment by cpeters** [comment]
For now.

**Comment by ohadlevy** [comment]
any issues with this pr (and similars)?

**Comment by domcleal** [comment]
No further issues, I was just asking so as not to waste time by trying to merge lots of conflicting PRs.

Merged and pushed live, thanks @cpeters.

**Pull request merged**
