### PR TITLE
Upgraded redmine to 2.6.6

### PR DESCRIPTION
**Pull request by ShimShtein**
Did some dry run tests, the system gets started in openshift. More testing needed before the merge.
Removed unused plugin: redmine_dashboard, if the plugin is still in use, I will readd it back.

### CODE REVIEW

**Comment by domcleal** [comment]
Looks like you've copied the contents of Redmine into the repo, could you use a merge instead from upstream's (see repo's fork) master branch?

**Comment by ShimShtein** [comment]
I can merge from the repo, but the we are not using the latest version. We need a different branch: 2.6-stable there.

**Comment by domcleal** [comment]
Merge a specific tag or commit.

**Comment by ShimShtein** [comment]
Merged the remote branch from git

**Comment by domcleal** [comment]
Looks good, thanks.  You mentioned about a dashboard plugin earlier, I can't see it - what was that about?

Is there any further testing you want to do?

The DB migrations look small to me, so easy to revert too if an upgrade goes bad.  I'd suggest we pick a day next week, e-mail -dev and -users and upgrade it then.

**Comment by ShimShtein** [comment]
Dashboard plugin: http://www.redminebacklogs.net/
It's about creating backlogs and managing scrum. AFAIK we are not using it.

**Comment by domcleal** [comment]
Ah, redmine_backlogs, yep.  We went through a phase of using it actively, but we still the releases field it provides, so it's needed.

**Comment by ShimShtein** [comment]
OK, I'll add it back

**Comment by domcleal** [comment]
As far as I can tell, you haven't removed it.

**Comment by domcleal** [comment]
Oh yes, please also update Gemfile.lock.

**Comment by ShimShtein** [comment]
Refreshed the Gemfile.lock.
Probably removed it only locally...
Anyway now it should work.

**Comment by domcleal** [comment]
You'll also need to update the submodule reference for the fix you put in redmine_backlogs.

**Comment by ShimShtein** [comment]
Reference updated.

**Comment by domcleal** [comment]
We'll do this on Tuesday 8th September, around 10am UTC.  I'll e-mail dev/users closer to the time.

**Comment by domcleal** [comment]
Thanks @ShimShtein.

**Pull request merged**
