### PR TITLE
Use bare git clones to sync from

### PR DESCRIPTION
**Pull request by ekohl**

### CODE REVIEW

**Comment by ekohl** [comment]
Based on https://www.redmine.org/projects/redmine/wiki/HowTo_keep_in_sync_your_git_repository_for_redmine but adapted to only sync requested branches.

**Comment by evgeni** [comment]
this makes the local branches go away. is that OK for our old redmine?

**Comment by ekohl** [comment]
I recall running redmine a long time ago (4 years?) and using bare clones there as well. Also note that the wiki content was written in 2012 so I think we're good.

**Comment by evgeni** [comment]
sounds good to me then.

**Pull request merged**
