### PR TITLE
Update to Redmine 5.1.3

### PR DESCRIPTION
**Pull request by evgeni**
____________________________________________________________________

Your contributions to Redmine are welcome!

Please **open an issue on the [official website]** instead of sending pull requests.

Since the development of Redmine is not conducted on GitHub but on the [official website] and core developers are not monitoring the GitHub repo, pull requests might not get reviewed.

For more detail about how to contribute, please see the wiki page [Contribute] on the [official website].

[official website]: https://www.redmine.org/
[Contribute]: https://www.redmine.org/projects/redmine/wiki/Contribute

### CODE REVIEW

**Comment by ekohl** [comment]
Any idea why Ruby 3.1 is failing? Was that already a problem previously?

**Comment by evgeni** [comment]
It seems unstable, if you re-run other tests might or might not fail

**Comment by evgeni** [comment]
Finally green \o/

**Review by ekohl — APPROVED** [review]

**Comment by evgeni** [comment]
I've opened  https://www.redmine.org/issues/40856 to track that upstream

**Pull request merged**
